Feature/modulize blog
mooore-digital/magento2-module-wordpress-integration-cms pull request #111
Opened 2023-03-01 10:55 UTC by poespas

2023-03-01 11:29 UTC, dlindeboom commented
Zou je mij kunnen uitleggen wat dit precies oplost deze pr?

2023-03-01 12:58 UTC, poespas commented
@dlindeboom

This PR (re)moves all blog-related things to it's own private module, creates a gernalized Wordpress HTTPClient so we can easily inherit from that, and generally clean up the code.

2023-03-02 08:07 UTC, dlindeboom commented on Model/HttpClient/Wordpress.php
> +    public const WP_JSON_URL_SUFFIX = '';
Like talked about, we need to make this class abstract and dont use a const

2023-03-03 10:18 UTC, dlindeboom requested changes

2023-03-03 11:06 UTC, dlindeboom requested changes

2023-03-03 11:06 UTC, dlindeboom commented on Model/HttpClient/Wordpress.php
> +            throw new \Exception("Type is required for HTTPClient");
Even import van maken en een eigen exception

2023-03-09 11:15 UTC, dlindeboom approved these changes

2023-03-10 10:18 UTC, merged