FIX: Add WordPress URL
mooore-digital/magento2-module-wordpress-integration-cms pull request #55
Opened 2021-06-09 11:54 UTC by erwinromkes

2021-06-09 12:07 UTC, tdgroot requested changes

2021-06-09 12:07 UTC, tdgroot commented on view/adminhtml/templates/cms/wordpressdata.phtml
> +        $(document).ready(function() {
Why does this need to be set on document ready? And why using jquery?

2021-06-09 12:07 UTC, tdgroot commented on ViewModel/WPCIData.php
> +        foreach ($this->remotePageRepository->getSites() as $site) {
What happens if no sites are available?

2021-06-09 12:07 UTC, tdgroot commented on ViewModel/WPCIData.php
> +    public function getWordPressUrl(): string
Should be `?string`

2021-06-09 12:07 UTC, tdgroot commented on ViewModel/WPCIData.php
> +        foreach ($this->remotePageRepository->getSites() as $site) {
```suggestion
        /** @var string|null $url */
        $url = null;
        foreach ($this->remotePageRepository->getSites() as $site) {
```

2021-06-09 12:07 UTC, tdgroot commented on ViewModel/WPCIData.php
> +    public function __construct(
Multiline not needed here

2021-06-09 12:07 UTC, tdgroot commented on ViewModel/WPCIData.php
> +    public function __construct(
```
    public function __construct(RemotePageRepository $remotePageRepository)
    {
```

2021-06-09 13:00 UTC, poespas commented on view/adminhtml/templates/cms/wordpressdata.phtml
> +            window.wordpressurl = '<?php echo $wordPressUrl; ?>';
What will happen when multiple CMS-envs are set to the installation? Will it only use one to calculate all editor URLs with?

2021-06-09 20:23 UTC, GrimLink commented on view/adminhtml/layout/cms_page_edit.xml
> +            <block name="wpci_data" before="before.body.end"
If you use multiline code make to wrap all attributes

2021-06-09 20:25 UTC, GrimLink commented on view/adminhtml/layout/cms_page_edit.xml
> +<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="admin-1column" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
Lines larger than 120 characters should be wrapped

2021-08-23 13:45 UTC, GrimLink commented
@erwinromkes this PR is closed since it is stale.
And not PR should merge to the main branch!
Please move all code logic back to the your branch from the latest develop branch instead.

2021-08-23 13:45 UTC, closed without merging